//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinic()
        {
            this.ClinicBookingTypes = new HashSet<ClinicBookingType>();
            this.ClinicDiscounts = new HashSet<ClinicDiscount>();
            this.ClinicServices = new HashSet<ClinicService>();
            this.Patients = new HashSet<Patient>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Doctors = new HashSet<Doctor>();
        }
    
        public System.Guid Id { get; set; }
        public string ClinicName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public Nullable<int> EntryOrderId { get; set; }
        public Nullable<int> BookingPeriod { get; set; }
        public Nullable<int> ConsultExpiration { get; set; }
        public string PrintDoctorName { get; set; }
        public string PrintDoctorDegree { get; set; }
        public string PrintClinicName { get; set; }
        public string PrintLogoUrl { get; set; }
        public string PrintAddress1 { get; set; }
        public string PrintAddress2 { get; set; }
        public string PrintAddress3 { get; set; }
        public string PrintPhone1 { get; set; }
        public string PrintPhone2 { get; set; }
        public string PrintPhone3 { get; set; }
        public Nullable<bool> IsAllDaysOn { get; set; }
        public string WorkDays { get; set; }
        public Nullable<bool> IsAllDaysSameTime { get; set; }
        public Nullable<System.DateTime> AllDaysTimeFrom { get; set; }
        public Nullable<System.DateTime> AllDaysTimeTo { get; set; }
        public Nullable<System.DateTime> SaturdayTimeFrom { get; set; }
        public Nullable<System.DateTime> SundayTimeFrom { get; set; }
        public Nullable<System.DateTime> MondayTimeFrom { get; set; }
        public Nullable<System.DateTime> TuesdayTimeFrom { get; set; }
        public Nullable<System.DateTime> WednesdayTimeFrom { get; set; }
        public Nullable<System.DateTime> ThursdayTimeFrom { get; set; }
        public Nullable<System.DateTime> FridayTimeFrom { get; set; }
        public Nullable<System.DateTime> SaturdayTimeTo { get; set; }
        public Nullable<System.DateTime> SundayTimeTo { get; set; }
        public Nullable<System.DateTime> MondayTimeTo { get; set; }
        public Nullable<System.DateTime> TuesdayTimeTo { get; set; }
        public Nullable<System.DateTime> WednesdayTimeTo { get; set; }
        public Nullable<System.DateTime> ThursdayTimeTo { get; set; }
        public Nullable<System.DateTime> FridayTimeTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicBookingType> ClinicBookingTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicDiscount> ClinicDiscounts { get; set; }
        public virtual SysEntryOrderValue SysEntryOrderValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicService> ClinicServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
