//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorExpens
    {
        public int Id { get; set; }
        public System.Guid DoctorId { get; set; }
        public int ExpenseItemId { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public decimal ExpenseAmount { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
    
        public virtual DoctorExpenseItem DoctorExpenseItem { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
