//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Bookings = new HashSet<Booking>();
            this.DoctorAnalysisValues = new HashSet<DoctorAnalysisValue>();
            this.DoctorBookingTypes = new HashSet<DoctorBookingType>();
            this.DoctorDetailedComplaintsValues = new HashSet<DoctorDetailedComplaintsValue>();
            this.DoctorDiagnosisValues = new HashSet<DoctorDiagnosisValue>();
            this.DoctorDiscounts = new HashSet<DoctorDiscount>();
            this.DoctorExaminationAreasValues = new HashSet<DoctorExaminationAreasValue>();
            this.DoctorExaminationsValues = new HashSet<DoctorExaminationsValue>();
            this.DoctorExpenseItems = new HashSet<DoctorExpenseItem>();
            this.DoctorExpenses = new HashSet<DoctorExpens>();
            this.DoctorGeneralComplaintsValues = new HashSet<DoctorGeneralComplaintsValue>();
            this.DoctorMedicinesValues = new HashSet<DoctorMedicinesValue>();
            this.DoctorOperationTypesValues = new HashSet<DoctorOperationTypesValue>();
            this.DoctorPharmacies = new HashSet<DoctorPharmacy>();
            this.DoctorPhysicalTherapyAreaValues = new HashSet<DoctorPhysicalTherapyAreaValue>();
            this.DoctorPhysicalTherapyValues = new HashSet<DoctorPhysicalTherapyValue>();
            this.DoctorRayAreasValues = new HashSet<DoctorRayAreasValue>();
            this.DoctorRaysValues = new HashSet<DoctorRaysValue>();
            this.DoctorServices = new HashSet<DoctorService>();
            this.PatientReferrals = new HashSet<PatientReferral>();
            this.Patients = new HashSet<Patient>();
            this.Clinics = new HashSet<Clinic>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public int SpecialtyId { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public string PatientRecordSections { get; set; }
        public string DiseasesQuestions { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string WhatsApp { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public string Instagram { get; set; }
        public Nullable<System.DateTime> AllDaysTimeFrom { get; set; }
        public Nullable<System.DateTime> AllDaysTimeTo { get; set; }
        public Nullable<int> BookingPeriod { get; set; }
        public Nullable<int> ConsultExpiration { get; set; }
        public Nullable<int> EntryOrderId { get; set; }
        public Nullable<System.DateTime> FridayTimeFrom { get; set; }
        public Nullable<System.DateTime> FridayTimeTo { get; set; }
        public Nullable<bool> IsAllDaysOn { get; set; }
        public Nullable<bool> IsAllDaysSameTime { get; set; }
        public Nullable<System.DateTime> MondayTimeFrom { get; set; }
        public Nullable<System.DateTime> MondayTimeTo { get; set; }
        public string PrintAddress1 { get; set; }
        public string PrintAddress2 { get; set; }
        public string PrintAddress3 { get; set; }
        public string PrintClinicName { get; set; }
        public string PrintDoctorDegree { get; set; }
        public string PrintDoctorName { get; set; }
        public string PrintLogoPublicId { get; set; }
        public string PrintLogoUrl { get; set; }
        public string PrintPhone1 { get; set; }
        public string PrintPhone2 { get; set; }
        public string PrintPhone3 { get; set; }
        public Nullable<System.DateTime> SaturdayTimeFrom { get; set; }
        public Nullable<System.DateTime> SaturdayTimeTo { get; set; }
        public Nullable<System.DateTime> SundayTimeFrom { get; set; }
        public Nullable<System.DateTime> SundayTimeTo { get; set; }
        public Nullable<System.DateTime> ThursdayTimeFrom { get; set; }
        public Nullable<System.DateTime> ThursdayTimeTo { get; set; }
        public Nullable<System.DateTime> TuesdayTimeFrom { get; set; }
        public Nullable<System.DateTime> TuesdayTimeTo { get; set; }
        public Nullable<System.DateTime> WednesdayTimeFrom { get; set; }
        public Nullable<System.DateTime> WednesdayTimeTo { get; set; }
        public string WorkDays { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorAnalysisValue> DoctorAnalysisValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorBookingType> DoctorBookingTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorDetailedComplaintsValue> DoctorDetailedComplaintsValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorDiagnosisValue> DoctorDiagnosisValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorDiscount> DoctorDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorExaminationAreasValue> DoctorExaminationAreasValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorExaminationsValue> DoctorExaminationsValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorExpenseItem> DoctorExpenseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorExpens> DoctorExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorGeneralComplaintsValue> DoctorGeneralComplaintsValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorMedicinesValue> DoctorMedicinesValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorOperationTypesValue> DoctorOperationTypesValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorPharmacy> DoctorPharmacies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorPhysicalTherapyAreaValue> DoctorPhysicalTherapyAreaValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorPhysicalTherapyValue> DoctorPhysicalTherapyValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorRayAreasValue> DoctorRayAreasValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorRaysValue> DoctorRaysValues { get; set; }
        public virtual SysEntryOrderValue SysEntryOrderValue { get; set; }
        public virtual SysDoctorsSpecialty SysDoctorsSpecialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorService> DoctorServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clinic> Clinics { get; set; }
    }
}
