//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Bookings = new HashSet<Booking>();
            this.PatientAnalysis = new HashSet<PatientAnalysi>();
            this.PatientDiagnosis = new HashSet<PatientDiagnosi>();
            this.PatientDiseases = new HashSet<PatientDiseas>();
            this.PatientExaminations = new HashSet<PatientExamination>();
            this.PatientGeneralComplaints = new HashSet<PatientGeneralComplaint>();
            this.PatientOperations = new HashSet<PatientOperation>();
            this.PatientRays = new HashSet<PatientRay>();
            this.PatientReferrals = new HashSet<PatientReferral>();
            this.PatientDetailedComplaints = new HashSet<PatientDetailedComplaint>();
            this.PatientPrescriptions = new HashSet<PatientPrescription>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.Guid ClinicId { get; set; }
        public int SeqNo { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> SocialStatusId { get; set; }
        public string Career { get; set; }
        public Nullable<int> GovernorateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<int> PrevMarriages { get; set; }
        public Nullable<int> PrevMarriagesPartner { get; set; }
        public string TreatmentHistory { get; set; }
        public string FamilyHistory { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> BodyMass { get; set; }
        public Nullable<int> BloodPressureId { get; set; }
        public Nullable<decimal> Temperature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Clinic Clinic { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAnalysi> PatientAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDiagnosi> PatientDiagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDiseas> PatientDiseases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientExamination> PatientExaminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientGeneralComplaint> PatientGeneralComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientOperation> PatientOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientRay> PatientRays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals { get; set; }
        public virtual SysBloodPressureValue SysBloodPressureValue { get; set; }
        public virtual SysSocialStatusValue SysSocialStatusValue { get; set; }
        public virtual SysCitiesValue SysCitiesValue { get; set; }
        public virtual SysGovernoratesValue SysGovernoratesValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDetailedComplaint> PatientDetailedComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientPrescription> PatientPrescriptions { get; set; }
    }
}
