//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnosi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientDiagnosi()
        {
            this.PatientReferrals = new HashSet<PatientReferral>();
        }
    
        public int Id { get; set; }
        public System.Guid PatientId { get; set; }
        public int DiagnosisId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
    
        public virtual DoctorDiagnosisValue DoctorDiagnosisValue { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual SysDiseaseGradesValue SysDiseaseGradesValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals { get; set; }
    }
}
