//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAnalysi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientAnalysi()
        {
            this.PatientAnalysisFiles = new HashSet<PatientAnalysisFile>();
        }
    
        public int Id { get; set; }
        public System.Guid PatientId { get; set; }
        public int AnalysisId { get; set; }
        public string RequestNote { get; set; }
        public Nullable<bool> IsHasResult { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string ResultText { get; set; }
        public Nullable<int> ResultGradeId { get; set; }
        public string ResultNote { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
    
        public virtual DoctorAnalysisValue DoctorAnalysisValue { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual SysDiseaseGradesValue SysDiseaseGradesValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAnalysisFile> PatientAnalysisFiles { get; set; }
    }
}
