//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public Nullable<decimal> SignUpFee { get; set; }
        public Nullable<int> RenewalTypeId { get; set; }
        public Nullable<decimal> AnnualRenewalFee { get; set; }
        public Nullable<decimal> MonthlyRenewalFee { get; set; }
        public Nullable<int> GracePeriodDays { get; set; }
        public Nullable<int> MaxUsers { get; set; }
        public Nullable<int> MaxBookingsMonthly { get; set; }
        public Nullable<int> MaxFilesMonthlyMB { get; set; }
        public Nullable<int> MaxFileSizeMB { get; set; }
    
        public virtual SysRenewalTypeValue SysRenewalTypeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
