//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.SubscriptionPayments = new HashSet<SubscriptionPayment>();
        }
    
        public int Id { get; set; }
        public System.Guid SubscriberId { get; set; }
        public int SubscriberTypeId { get; set; }
        public int PlanId { get; set; }
        public Nullable<int> SubscriptionTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public Nullable<decimal> SignUpFee { get; set; }
        public Nullable<decimal> AnnualRenewalFee { get; set; }
        public Nullable<decimal> MonthlyRenewalFee { get; set; }
        public Nullable<int> GracePeriodDays { get; set; }
        public Nullable<int> MaxUsers { get; set; }
        public Nullable<int> MaxBookingsMonthly { get; set; }
        public Nullable<int> MaxFilesMonthlyMB { get; set; }
        public Nullable<int> MaxFileSizeMB { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual SysSubscriberTypeValue SysSubscriberTypeValue { get; set; }
        public virtual SysSubscriptionTypeValue SysSubscriptionTypeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionPayment> SubscriptionPayments { get; set; }
    }
}
